# Generated by Django 5.0.6 on 2024-07-12 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_dir', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad_dir', models.CharField(max_length=255)),
                ('barrio_dir', models.CharField(max_length=255)),
                ('calle_dir', models.CharField(max_length=255)),
                ('numero_dir', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id_ins', models.AutoField(primary_key=True, serialize=False)),
                ('km', models.PositiveIntegerField()),
                ('nivel_gasolina', models.CharField(max_length=50)),
                ('plumas', models.BooleanField(default=False)),
                ('antena', models.BooleanField(default=False)),
                ('radio', models.BooleanField(default=False)),
                ('encendedor', models.BooleanField(default=False)),
                ('espejos', models.BooleanField(default=False)),
                ('gata', models.BooleanField(default=False)),
                ('llave_de_ruedas', models.BooleanField(default=False)),
                ('llanta_emergencia', models.BooleanField(default=False)),
                ('parlantes', models.BooleanField(default=False)),
                ('direccionales', models.BooleanField(default=False)),
                ('manubrios', models.BooleanField(default=False)),
                ('parabrisas', models.BooleanField(default=False)),
                ('t_seguridad', models.BooleanField(default=False)),
                ('tapa_radiador', models.BooleanField(default=False)),
                ('mandos_funcionales', models.BooleanField(default=False)),
                ('cenicero', models.BooleanField(default=False)),
                ('palanca', models.BooleanField(default=False)),
                ('herramientas', models.BooleanField(default=False)),
                ('botiquin', models.BooleanField(default=False)),
                ('tapa_gasolina', models.BooleanField(default=False)),
                ('lunas', models.BooleanField(default=False)),
                ('faros', models.BooleanField(default=False)),
                ('extintor', models.BooleanField(default=False)),
                ('tapa_cubas', models.BooleanField(default=False)),
                ('triangulos', models.BooleanField(default=False)),
                ('emblemas', models.BooleanField(default=False)),
                ('placas', models.BooleanField(default=False)),
                ('moquetas', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_ord', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ord', models.DateTimeField()),
                ('fecha_fin_ord', models.DateTimeField(blank=True, null=True)),
                ('numero_ord', models.IntegerField()),
                ('observaciones_ord', models.TextField()),
                ('estado_ord', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('ESPERANDO_REPUESTOS', 'Esperando Repuestos'), ('COMPLETADA', 'Completada'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_ser', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ser', models.CharField(max_length=255, unique=True)),
                ('descripcion_ser', models.TextField()),
                ('precio_ser', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tall', models.CharField(max_length=255)),
                ('descripcion_tall', models.TextField()),
                ('logo_tall', models.FileField(blank=True, null=True, upload_to='Taller')),
                ('direccion_tall', models.CharField(max_length=100)),
                ('email_tall', models.EmailField(max_length=254)),
                ('telefono_tall', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usr', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('MECANICO', 'Mecánico')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cli', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cli', models.CharField(max_length=255)),
                ('apellido_cli', models.CharField(max_length=255)),
                ('ci_cli', models.CharField(max_length=10, unique=True)),
                ('telefono_cli', models.CharField(max_length=20)),
                ('email_cli', models.EmailField(max_length=254, unique=True)),
                ('dir_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Danio',
            fields=[
                ('id_dan', models.AutoField(primary_key=True, serialize=False)),
                ('x_pos', models.FloatField()),
                ('y_pos', models.FloatField()),
                ('descripcion_dan', models.TextField()),
                ('inspeccion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.inspeccion')),
            ],
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='orden_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestion.orden'),
        ),
        migrations.CreateModel(
            name='OrdenRepuesto',
            fields=[
                ('id_rep', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rep', models.CharField(max_length=255)),
                ('descripcion_rep', models.TextField()),
                ('precio_rep', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_rep', models.IntegerField()),
                ('subtotal_rep', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.orden')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id_ord_ser', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.orden')),
                ('servicio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='Gestion.usuario'),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_veh', models.AutoField(primary_key=True, serialize=False)),
                ('marca_veh', models.CharField(max_length=255)),
                ('modelo_veh', models.CharField(max_length=255)),
                ('placa_veh', models.CharField(max_length=20, unique=True)),
                ('anio_veh', models.IntegerField()),
                ('chasis_veh', models.CharField(max_length=255, unique=True)),
                ('color_veh', models.CharField(max_length=255)),
                ('cli_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestion.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='vehiculo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='Gestion.vehiculo'),
        ),
    ]
