# Generated by Django 5.0.6 on 2024-07-13 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenservicio',
            name='servicio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestion.servicio'),
        ),
    ]
