# Generated by Django 5.0.6 on 2024-07-27 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_cliente_deleted_at_cliente_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='chasis_veh',
        ),
    ]
