# Generated by Django 5.0.6 on 2024-07-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0006_usuario_groups_usuario_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
    ]
