# Generated by Django 5.0.6 on 2024-08-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0007_remove_usuario_groups_remove_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='is_deleted',
        ),
    ]
