# Generated by Django 5.0.6 on 2024-08-11 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0010_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Taller',
        ),
    ]
