from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name="index"),
    path('login/',views.login_view,name="login"),
    path('administrador/',views.home,name="home"),
    path('mecanico/',views.home2,name="home2"),
    path('lista_usuarios/', views.index1, name="index1"),
    path('guardar_usuario/', views.guardarUsuario, name="guardarUsuario"),
    path('registrar_usuario/', views.registrarUsuario),
    path('actualizar_usuario/<int:id_usr>/',views.actualizarUsuario,name="actualizarUsuario"),
    path('eliminar_usuario/<int:id>', views.eliminarUsuario, name="eliminarUsuario"),
    path('lista_clientes/',views.listaClientes,name="listaClientes"),
    path('guardar_cliente/',views.guardarCliente, name="guardarCliente"),
    path('registrar_cliente/',views.registrarCliente),
    path('eliminar_cliente/<int:id>',views.eliminarCliente),
    path('actualizar_cliente/<int:id_cli>/',views.actualizarCliente,name="editarCliente"),
    path('lista_servicios/',views.listaServicios,name="listaServicios"),
    path('guardar_servicio/',views.guardarServicio,name="guardarServicio"),
    path('registrar_servicio/',views.registrarServicio),
    path('eliminar_servicio/<int:id>/',views.eliminarServicio),
    path('obtener_servicio/<int:id>/',views.obtenerServicio,name='obtenerServicio'),
    path('actualizar_servicio/',views.actualizarServicio),
    path('lista_vehiculos/',views.listaVehiculos,name="listaVehiculos"),
    path('guardar_vehiculo/',views.guardarVehiculo,name="guardarVehiculo"),
    path('registrar_vehiculo/',views.registrarVehiculo),
    path('eliminar_vehiculo/<int:id>/',views.eliminarVehiculo),
    path('actualizar_vehiculo/<int:id_veh>/',views.actualizarVehiculo,name="editarVehiculo"),
    path('guardar_orden/',views.guardarOrden,name="ordenCliente"),
    path('registrar_orden/',views.registrarOrden),
    path('listar_ordenes/',views.listarOrdenesNoFinalizadas,name="listarOrdenes"),
    path('registrar_inspeccion/',views.registrarDanios,name="registrarDanios"),
    path('guardar_inspeccion/',views.guardarDanios),
    path('lista_inspeccion/',views.listarDanios,name="listarDanios"),
    path('editar_inspeccion/<int:id_ord>/',views.obtenerDanios),
    path('actualizar_inspeccion/',views.actualizarDanios),
    path('eliminar_inspeccion/<int:id_ins>/',views.eliminarDanios),
    path('lista_detalles/',views.listarDetalleOrden,name="listaDetalle"),
    path('guardar_repuestos/',views.guardarDetalle,name="registrarDetalle"),
    path('registrar_repuestos/',views.guardarRepuestos),
    path('obtener_orden/<int:id>/',views.obtenerOrden),
    path('editar_orden/',views.editarOrden),
    path('eliminar_orden/<int:id>/',views.eliminarOrden),
    path('guardar_orden_2/',views.guardarOrden2, name="guardarOrden2"),
    path('registrar_orden_2/',views.registrarOrden2),
    path('obtener_repuestos/<int:id>/',views.obtenerRepuestos),
    path('editar_repuestos/',views.editarRepuestos),
    path('eliminar_repuestos/<int:id>/',views.eliminarRepuestos),
    path('eliminar_detalle_m/<int:id>/',views.eliminarRepuestosM),
    path('detalle_orden/<int:id>/',views.detalleOrden),
    path('detalleInspeccion/<int:id>/',views.reporte_inspeccion),
    path('login/',views.login_view,name="login"),
    path('logout/',views.logout,name="logout"),
    path('lista_ordenes_m/',views.ordenes_mecanico,name="ordenesM"),
    path('aceptar_orden/<int:id_ord>/', views.aceptar_orden, name='aceptar_orden'),
    path('lista_progreso/',views.lista_progreso,name="listaProgreso"),
    path('cambiar_estado_orden/<int:id_ord>/<str:nuevo_estado>/', views.cambiar_estado_orden, name='cambiar_estado_orden'),
    path('listar_inspecciones/',views.listar_inspecciones,name="listarInspeccionM"),
    path('guardar_inspeccion_m/',views.guardarDaniosM),
    path('actualizar_inspeccion_m/',views.actualizarDaniosM),
    path('editar_inspeccion_m/<int:id_ord>/',views.obtenerDaniosM),
    path('actualizar_inspeccion_m/',views.actualizarDaniosM),
    path('eliminar_inspeccion_m/<int:id_ins>/',views.eliminarDaniosM),
    path('ordenes_m/',views.listar_ordenes_completadas,name="ordenesCompletas"),
    path('usuarios_eliminados/',views.listaUsuariosEliminados,name="usuariosEliminados"),
    path('restaurar_usuario/<int:id>/',views.restaurarUsuario),
    path('servicios_eliminados/',views.serviciosEliminados,name="serviciosEliminados"),
    path('restaurar_servicio/<int:id>/',views.restaurarServicio),
    path('ordenes_finalizadas/',views.listarOrdenesFinalizadas,name='ordenesFinalizadas'),
    path('buscar_vehiculo/', views.buscar_vehiculo, name='buscar_vehiculo'),
    path('obtener_nombres_repuestos/', views.obtener_nombres_repuestos, name='obtener_nombres_repuestos'),
    path('obtener_marcas/', views.obtener_marcas, name='obtener_marcas'),
    path('obtener_modelos/', views.obtener_modelos, name='obtener_modelos'),
    path('obtener_colores/', views.obtener_colores, name='obtener_colores'),
    path('finalizar_orden/<int:id>/',views.finalizarOrden),
    path('agregar_detalle_m/<int:id>/', views.agregarDetalleM, name='agregar_detalle_m'),
    path('registrar_repuestos_m/', views.guardarRepuestosM, name='registrar_repuestos_m'),
    path('obtener_detalle_m/<int:id>/', views.obtenerRepuestosM, name='obtener_detalle_m'),
    path('editar_detalle_m/',views.editarRepuestosM,name="editar_repuestos_m"),
    path('recuperar-contraseña/', views.password_reset_request, name='password_reset_request'),
    path('reset-password/<uuid:token>/', views.reset_password, name='reset_password'),
    path('configurar_sitio/', views.configurar_sitio, name='configurar_sitio'),
    
]
handler404 = 'Aplicaciones.Gestion.views.custom_404_view'
handler500 = 'Aplicaciones.Gestion.views.custom_500_view'

